### ISSUE TITLE
Patch versions of Docker containers aren't available on Docker Hub

### ISSUE THREAD

**Issue by wbushey** [streamthoughts/jikkou#105]
**Describe the bug**
Only the minor versions (e.g. 0.12.0, 0.11.0) of recent releases are available on [Docker Hub](https://hub.docker.com/r/streamthoughts/jikkou/tags) . Patch versions (e.g. 0.12.2, 0.11.1) since 0.7.1 are not available on Docker Hub.

**To Reproduce**

`docker pull streamthoughts/jikkou:0.12.2`

**Expected behavior**

Version 0.12.2 of the jikkou docker container is downloaded

**Comment by fhussonnois** [comment]
Hi @wbushey, thank you for reporting that issue. Patch versions were uploaded on docker-hub.
