### ISSUE TITLE
IAM authorization for MSK?

### ISSUE THREAD

**Issue by njlr** [streamthoughts/jikkou#168]
Hello, 

I am wondering if there is any documentation around connecting Jikkou to Amazon Managed Kafka Service (MSK) using IAM roles?

Amazon provide a module for this here: https://github.com/aws/aws-msk-iam-auth

I am using the Docker image `streamthoughts/jikkou:latest@sha256:f8b4230752d276330ee071e7d4160e206fd257f4d66bc8efac1c7ed6dafe1197`

**Comment by chrisoberle** [comment]
I was to get this working by including the required iam jar and rebuilding.      see https://github.com/streamthoughts/jikkou/compare/main...chrisoberle:jikkou:main 

Then i configured the aws cli with the appropriate creds and used a jikkou config like this:

```
❯ cat ~/.jikkou/config
{
  "currentContext" : "sandbox",
  "sandbox" : {
    "configFile" : null,
    "configProps" : {
      "kafka.client.security.protocol" : "SASL_SSL",
      "kafka.client.sasl.mechanism" : "AWS_MSK_IAM",
      "kafka.client.sasl.jaas.config" : "software.amazon.msk.auth.iam.IAMLoginModule required;",
      "kafka.client.sasl.client.callback.handler.class" : "software.amazon.msk.auth.iam.IAMClientCallbackHandler",
      "kafka.client.bootstrap.servers" : "SASL IAM BOOTSTRAP SERVERS"
    }
  }
}
```

**Comment by joschi** [comment]
I think this has been resolved in https://github.com/streamthoughts/jikkou/releases/tag/v0.22.0 via https://github.com/streamthoughts/jikkou/pull/212.
