### ISSUE TITLE
What is the difference between API version kafka.jikkou.io/v1beta2 and 1 ?

### ISSUE THREAD

**Issue by njlr** [streamthoughts/jikkou#169]
What is the difference between API version `kafka.jikkou.io/v1beta2` and `1`?

The documentation has examples with each and it is not clear what should be used.

**Comment by fhussonnois** [comment]
Hi @njlr, Jikkou API is currently under heavy refactoring (btw, I hope to release a new version in a couple of week that may include some breaking changes). 

There are errors in the documentation that I will fix but you should use the `kafka.jikkou.io/v1beta2`.

**Comment by njlr** [comment]
Thanks @fhussonnois that clears things up!
