### ISSUE TITLE
Feature: Add extension to manage connectors for Kafka Connect

### ISSUE THREAD

**Issue by fhussonnois** [streamthoughts/jikkou#178]

**Comment by bsvicente** [comment]
@fhussonnois do you need some help?

**Comment by fhussonnois** [comment]
Hi @bsvicente, thank you very much, I suppose you'd like to contribute to the project and I'd be very grateful. Adding a new extension to support Kafka Connect should not be to complicated and similar to the SchemaRegistry extension.

**Comment by bsvicente** [comment]
Sorry i won't be able to help with this task for at least this month
