### ISSUE TITLE
Change the reconciliation mode? 

### ISSUE THREAD

**Issue by Akash-Mair** [streamthoughts/jikkou#188]
Hey!

After reading the [docs](https://streamthoughts.github.io/jikkou/docs/concepts/reconciliation/) about reconciliation modes I would like to change the mode to `UPDATE` I'm not sure how to do this?

Is this something in the YAML or maybe an env var I can pass through? 

Many thanks!

**Comment by Akash-Mair** [comment]
Just seen that I can pass the `--kind` subcommand after `apply` :)

**Comment by fhussonnois** [comment]
Hi @Akash-Mair, I'm sorry, the documentation is still in working progress ^^. The reconciliation mode is automatically set depending on the CLI command: 

- CREATE = `jikkou create`
- UPDATE = `jikkou update`
- DELETE = `jikkou delete`
- APPLY_ALL = `jikkou update`
