### ISSUE TITLE
Unknown option: '--config=kafka.client.bootstrap.servers=localhost:9092'

### ISSUE THREAD

**Issue by CarmineDeloitte** [streamthoughts/jikkou#228]
Hello, 

I'm trying to set the right config for jikkou, using cli command as per [documentation](https://streamthoughts.github.io/jikkou/docs/introduction/getting_started/)

When I try to run this command 

`jikkou config set-context localhost --config=kafka.client.bootstrap.servers=localhost:9092`

I'm getting this error 

`Unknown option: '--config=kafka.client.bootstrap.servers=localhost:9092'
Possible solutions: --config-props-file, --config-props, --config-file`

`jikkou --version 
Jikkou version v0.21.0`

**Comment by fhussonnois** [comment]
Document was fixed with the good parameter: `--config-props`
