### ISSUE TITLE
Support Apicurio with Confluent compatibility api.

### ISSUE THREAD

**Issue by bsvicente** [streamthoughts/jikkou#233]
**Describe the bug**
Using Apicurio Registry with Confluent compatibility api, /subjects/{subject}/version/latest returns an element called references that's is not recognized in SubjectSchema 

**To Reproduce**
Run jikkou apply with apicurio registry, using /apis/ccompat/v7 , trying to update an schema

**Expected behavior**
Update the schema

**Runtime environment**
 - OS: [e.g. Ubuntu]
 - Jikkou: [e.g. 0.24.0]

**Comment by bsvicente** [comment]
[Bug] reference list should be type of SubjectSchemaReference

**Comment by bsvicente** [comment]
fix: https://github.com/streamthoughts/jikkou/pull/321

**Comment by bsvicente** [comment]
@fhussonnois may i need to do smt more?

**Comment by fhussonnois** [comment]
Fixed in v0.33.0
