### ISSUE TITLE
Feature: a single launch to do all

### ISSUE THREAD

**Issue by gquintana** [streamthoughts/jikkou#28]
In the current release, I have to run kafka-specs several times:
- topics create
- topics alter
- topics delete
- acls create
Each run requires to initiate a connection to Kafka, fetch the actual state and compare it to the expected state.

Being able to do everything in one go would be very interesting.
Instead of running:
```
kafka-specs <topics|acls> <create|alter|delete>
```
I would run 
```
kafka-specs --entity-type topics,acls  --operation create,alter,delete
or even
kafka-specs --entity-type all  --operation all

```

**Comment by fhussonnois** [comment]
Kafka Specs v0.5.0 adds new subcommand `apply` for topics, and ACLs  :

```
$ ./kafka-specs-0.5.0/bin/kafka-specs topics apply --file-path kafka-specs-topics.yml
``` 

The subcommand `apply` accepts the following params: 

 * ` --delete-config-orphans` : Delete config entries that exist on the cluster but are absent from your specs-file.
 * ` --delete-topic-orphans` : Delete Topics which exist on the cluster but absent from your specs-files
