### ISSUE TITLE
jikkou health get all requires aiven token

### ISSUE THREAD

**Issue by eigakow** [streamthoughts/jikkou#288]
health get all command gives error, seems there is dependency introduced on aiven configuration when not using aiven.

Tested with 0.29.0 version and reproduced on two different environments. Using dummy kafka image (blacktop/kafka) for testing without authentication and well as docker compose stack from jikkou repo.

The error message appeared after switching from jikkou 0.24.0 version, no issue with older version

**To Reproduce**
```
$ jikkou config  current-context
Using context 'local-cmd'

 KEY          VALUE                                               
 ConfigFile                                                       
 ConfigProps  {"kafka.client.bootstrap.servers":"kafka:9092"} 

$ jikkou health get all
Error: No value present for param 'aiven.tokenAuth' (Aiven Bearer Token. Tokens can be obtained from your Aiven profile page)
```
**Expected behavior**
Get a correct output

**Runtime environment**
 - OS: macos, alpine 3.18
 - Jikkou: 0.29.0
 - Kafka Cluster Version: reproduced on two env, image blacktop/kafka (kafka version 3.3.1) and one provided in this repo

**Additional context**

**Comment by fhussonnois** [comment]
Hi @eigakow,

Thank you for reporting this issue. We should introduce in future version a way to enable/disable extensions. 

Currently, when using `all` option Jikkou attempts get all known health indicators. Until, we fix that issue, I recommand to use the following command: `jikkou health get kafkabroker`
