### ISSUE TITLE
Dockerfile should not define USER

### ISSUE THREAD

**Issue by singhbaljit** [streamthoughts/jikkou#314]
**Describe the bug**
The official Jikkou images define a `USER` in the Dockerfile. While it is usually a good practice to run containers with non-root, this is not great in CI/CD pipelines. We're unable install additional packages due to non-root user.

**To Reproduce**
1. Launch the container
2. Install a new package, i.e. `apk add ...`

**Expected behavior**
Container should run as `root` by default so users can add additional packages in their CI pipelines

**Runtime environment**
 - Jikkou: 0.30.0

**Additional context**
Since our pipelines run on Kubernetes, we can't easily change the user at runtime (unlike `docker run ...`).

**Comment by fhussonnois** [comment]
Hi @singhbaljit, you can still switch the `USER` to root when building new image from jikkou.

```
FROM streamthoughts/jikkou

USER root

RUN apk add --update curl && \
    rm -rf /var/cache/apk/*
```

**Comment by singhbaljit** [comment]
Yes, but that requires maintaining/hosting our own image. Using the official image is less overhead and preferred solution.

**Comment by fhussonnois** [comment]
For security purposes, it's a good practice to always run Docker images run as non-root. In addition, most of secured environements block containers running as root by default. For those reasons and to be secured by designed the Dockerfile will not be changed.
