### ISSUE TITLE
CLI native image v0.31.0 fails to run on Mac M1 

### ISSUE THREAD

**Issue by chrisoberle** [streamthoughts/jikkou#322]
**Describe the bug**
Jikkou CLI fails with the following error on an M1 Mac.

> Please rebuild the executable with an appropriate setting of the -march option.The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].

**To Reproduce**
From an M1 mac, execute any jikkou command

**Expected behavior**
CLI commands should run without error.

**Screenshots/Configs**

**Runtime environment**
 - OS: MacOS Sonoma 14.1 - Apple M1 Pro
 - Jikkou: 0.31.0-osx-x86_64
 - Docker version: N/A
 - Kafka Cluster Version: N/A

**Additional context**
Early access release installed on 11/6/23 or 11/7/23 didn't have this issue.

**Comment by davidlanouette** [comment]
I did a little bit of research.

It looks like the release process only targets `macOS-latest` - which is based on the x86 CPU machines.  However, it looks like they have beta support for building on M1 CPU's.  See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

I don't know if the cost will be an issue or not.

HTH.

**Comment by fhussonnois** [comment]
I've looked at other opensource projects building native images and it seems that one solution to this problem is the use of a rosetta terminal on Mac M1: https://apple.stackexchange.com/questions/428768/on-apple-m1-with-rosetta-how-to-open-entire-terminal-iterm-in-x86-64-architec

**Comment by chrisoberle** [comment]
It seems weird that the early access version of 0.31.0 but the released version doesn't.   I couldn't find anything in the changelog to suggest a reason for that.  Do you have any ideas?

**Comment by fhussonnois** [comment]
I finally figured out the problem. Unfortunatly, the issue depends on the GitHub runner used to build the native image.  If the runner has a new CPU architecture (i.e., x86-64-v4) but you are running on an older one then some instructuction may be missing. It seems, I can configure a new GraalVM option (`-march=compatibility`) to force the native compilation to use an older instruction set, increasing the chance of compatibility.

**Comment by chrisoberle** [comment]
fixed in 0.32 early access.   ty @fhussonnois !    going to try out that the new logging feature now.
