### ISSUE TITLE
Gitlab ci/cd error when using jikkou image

### ISSUE THREAD

**Issue by ajolakoskiMyne** [streamthoughts/jikkou#325]
Log from gitlab ci/cd when i updated docker image from 0.24.0 to 0.31.0

$ /app/jikkou config set-context aiven --config-file="$KAFKA_CLUSTER_CONF"

The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].

Please rebuild the executable with an appropriate setting of the -march option.

How i can solve this issue ?

**Comment by chrisoberle** [comment]
Noted this issue here as well...  https://github.com/streamthoughts/jikkou/issues/322

@ajolakoskiMyne consider adding details about your container runtime and such.   The information here is pretty sparse and may not be enough to help diagnose.

**Comment by ajolakoskiMyne** [comment]
We solve the issue with migrating gitlab on new server that have support for this  CPU features that was mentioned in the log.
