### ISSUE TITLE
Support on MAC machine m2

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [streamthoughts/jikkou#334]
I have been trying to install and run it on the Mac machine m2. Installed from 

wget https://github.com/streamthoughts/jikkou/releases/download/v0.31.0/jikkou-0.31.0-osx-x86_64.zip

But running jikkou from the bin says following

The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.%

Also, running with java binaries, it shows ' '/jikkou-connect.conf is not found. Please help to install and make it run on mac and then kubernetes with docker

**Comment by fhussonnois** [comment]
Jikkou 0.32.1 add a better support for CPU features compatibiity. Using the latest version should fix the issue.
