### ISSUE TITLE
Using Jikkou to manage kafka-connectors without managing kafka-connect

### ISSUE THREAD

**Issue by arnoldyahad** [streamthoughts/jikkou#370]
Hey,
We want to start using JIkkou for managing in-code our kafka-connectors.
We already have deployments for our kafka-connect services and we don't want to use Jikkou(or any other solution) to manage our kafka-connect.

same as mentioned on strimzi (https://github.com/orgs/strimzi/discussions/9360) we want to have a solution only to manage kafka-connectors in code.

Is it possible to do with Jikkou? (to have my own deployed kafka-connect service and only managed the kafka-connectots with jikkou)

**Comment by fhussonnois** [comment]
Hi @arnoldyahad, Jikkou is actually designed to manage only Kafka Connectors (Kafka Connect clusters being something more infrastructure-related). Here is a blog post about managing kafka connectors with jikkou: https://medium.com/@fhussonnois/kafka-connect-jikkou-easily-manage-kafka-connectors-d4dd2b8a560c
