### ISSUE TITLE
Jikkou API server - kafka-connect support

### ISSUE THREAD

**Issue by arnoldyahad** [streamthoughts/jikkou#455]
Hey Jikkout team, 
I want to use Jikkou API Server in our EKS cluster in-order to manage multiple kafka-connectors configurations. 

i have read the instructions in the readme and [in this medium article ](https://medium.com/@fhussonnois/jikkou-0-31-0-use-the-declarative-power-of-rest-apis-to-manage-apache-kafka-60b82aa1c248)

Here is an output of the jikkou API version(latest 0.34): 
```
curl -sX GET http://localhost:28082/  | jq .
{
  "version": "0.34.0",
  "build_time": "2024-05-01T22:00:55+0000",
  "commit_id": "1d3829c69adfb6b4ccbd23ba0ded1788946ed513",
  "_links": {
    "self": {
      "href": "/",
      "templated": false
    },
    "get-apis": {
      "href": "/apis",
      "templated": false
    }
  }
}
```

i've used the `/apis` endpoint to get whats available:
```
{
  "kind": "ApiGroupList",
  "apiVersion": "v1",
  "groups": [
    {
      "name": "kafka.jikkou.io",
      "versions": [
        {
          "groupVersion": "kafka.jikkou.io/v1beta1",
          "version": "v1beta1",
          "metadata": {
            "_links": {
              "self": {
                "href": "/apis/kafka.jikkou.io/v1beta1",
                "templated": false
              }
            }
          }
        },
        {
          "groupVersion": "kafka.jikkou.io/v1beta2",
          "version": "v1beta2",
          "metadata": {
            "_links": {
              "self": {
                "href": "/apis/kafka.jikkou.io/v1beta2",
                "templated": false
              }
            }
          }
        }
      ]
    }
  ],
  "_links": {
    "self": {
      "href": "/apis",
      "templated": false
    }
  }
}
```

after checking both groups with:
```
curl -sX GET http://localhost:28082/apis/kafka.jikkou.io/v1beta2 
curl -sX GET http://localhost:28082/apis/kafka.jikkou.io/v1beta1
```
(output is too long)

i've noticed there is no `KafkaConnector` or anything related to kafka-connect at all. 

so i have a couple of questions: 
Does the API Server support kafka-connect? 
Is there a plan to make it support kafka-connect? (if needed i can open an issue) 

Thanks a lot!

**Comment by fhussonnois** [comment]
Hi @arnoldyahad, did you enable the KafkaConnector provider ? See doc: https://www.jikkou.io/docs/jikkou-api-server/configuration/server_configuration/#enabling-specific-extension-providers

**Comment by arnoldyahad** [comment]
thanks a lot @fhussonnois 
im using the kafkaConnector through the dockerized version of it, taken from the [documentation](https://www.jikkou.io/docs/jikkou-api-server/install/#from-docker-hub) 

```
$ docker run -it streamthoughts/jikkou-api-server:main
```

i see in the doc you provided that there is a way to enable it through application.conf file, but i don't see it in my docker

is there any method to enable it through api request? or to pass an environment variable to enable it? 
something like:
```
$ docker run -it streamthoughts/jikkou-api-server:main -e ENABLE_INTEGRATIONS=true
```

or by running an api command? 
```
curl -sX GET http://localhost:28082/enable_extentions -H "Accept: application/json"  | jq .
```
(although a variable is much better way and can be persisted in code) 

if those 2 options dont exist at the moment, what is the best way for me to proceed? is it adding a /etc/application.conf on my own (to use docker-compose for that)? 

thanks a lot for your help!

**Comment by fhussonnois** [comment]
Hi @arnoldyahad, sorry for my late reply:

You need to create an `application.yaml` file with : 
```
micronaut:
  server:
    port: 8080
jikkou:
  extension.providers:
    default.enabled: true # -> enable all extensions by default
```

Then: 

```
docker pull streamthoughts/jikkou-api-server:latest
docker run -it \
    -p 8080:8080 \
    -v /your-path/application.yaml:/app/resources/application.yaml
    streamthoughts/jikkou-api-server:latest
```
