### ISSUE TITLE
NPE KafkaPrincipalRole io.streamthoughts.jikkou.core.reconciler.DefaultChangeResult["description"])

### ISSUE THREAD

**Issue by Antoine7773** [streamthoughts/jikkou#461]
**Describe the bug**
When trying to apply the KafkaPrincipalRole example described here :https://www.jikkou.io/docs/providers/kafka/resources/acls/#example-1
I am getting the following error : _Error: JikkouRuntimeException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.streamthoughts.jikkou.core.reconciler.DefaultChangeResult["description"])_
Jikkou version used 0.34.0

**To Reproduce**
Copy the example of KafkaPrincipalRole https://www.jikkou.io/docs/providers/kafka/resources/acls/#example-1
Paste into kafka-acls.yaml
use jikkou command apply -f kafka-acls.yaml 
`docker run -it --net host --mount type=bind,source="$(pwd)"/jikkouconfig,target=/etc/jikkou/config --mount type=bind,source=<path_to_file>/kafka-acls.yaml,target=/etc/jikkou/kafka-acls/ streamthoughts/jikkou:0.34.0 apply -f /etc/jikkou/kafka-acls/ --dry-run`

**Expected behavior**
Would expect to create the PrincipalRole
Like with https://www.jikkou.io/docs/providers/kafka/resources/acls/#example where it is working well.

**Runtime environment**
 - OS: Ubuntu
 - Jikkou: 0.34.0
 - Docker version: 26.01.3
 - Kafka Cluster Version: cp-7.5.0

**Additional context**
Found an other issue that might be related https://github.com/streamthoughts/jikkou/issues/190
But the link returns 404

**Comment by fhussonnois** [comment]
Hi @Antoine7773, thank you very for reporting this issue. It's seems an NPE was thrown when no change was detected for that resource kind. You should be able to use the preview version. I've pushed a fix for that issue. Do not hesite to reopen this issue if needed.

**Comment by Antoine7773** [comment]
Hello @fhussonnois  
Thanks a lot for the quick reply. It is failing as well with version 0.33.* . No longer error using  jikkou:main image.
