### ISSUE TITLE
Add possibility to specify where jikkou will save it's conf file

### ISSUE THREAD

**Issue by micr01996** [streamthoughts/jikkou#470]
It's quite frustrating that there's no option to specify where Jikkou saves its configuration file. When setting up CI/CD, it often fails because the user doesn't have permission to modify the /etc/jikkou/config file.

**Comment by fhussonnois** [comment]
Hi @micr01996, 

By default, jikkou CLI try to read/write its configuration from   `~/.jikkou/config`. You can specify you own file by setting the environement variable `JIKKOUCONFIG` (e.g., `export JIKKOUCONFIG="/tmp/jikkou/config"`). 

Let me know if this is what you were looking for. Thanks.
