### ISSUE TITLE
SSL error with SASL_SSL security protocol

### ISSUE THREAD

**Issue by Antoine7773** [streamthoughts/jikkou#473]
**Describe the bug**
When trying to connect to cluster (Using **SASL_SSL security protocol**) with the below command I get and SSL error 
`docker run -it --net host --mount type=bind,source=./jikkou/jikkouconfig,target=/etc/jikkou/config --mount type=bind,source=./jikkou/kafka-topics.yaml,target=/etc/jikkou/kafka-topics --mount type=bind,source=./security/kafka/ssl/certifs/clients_certifs,target=/etc/jikkou/secrets streamthoughts/jikkou:0.34.0 create -f /etc/jikkou/kafka-topics/ --dry-run`

> 09:20:06.054 [kafka-admin-client-thread | adminclient-1] ERROR o.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:39092) failed authentication due to: SSL handshake failed
09:20:06.054 [main] ERROR i.s.j.k.internals.KafkaBrokersReady - Error while listing Kafka nodes: org.apache.kafka.common.errors.SslAuthenticationException: **SSL handshake failed**

Enabling TRACE logs to get more information I get 

> 09:19:16.372 [kafka-admin-client-thread | adminclient-1] ERROR o.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:39092) failed authentication due to: SSL handshake failed
09:19:16.372 [kafka-admin-client-thread | adminclient-1] WARN  o.a.k.c.a.i.AdminMetadataManager - [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: **PKIX path building failed**: sun.security.provider.certpath.SunCertPathBuilderException: **unable to find valid certification path to requested target**
	at java.base@21.0.3/sun.security.ssl.Alert.createSSLException(Alert.java:130)
.
.
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base@21.0.3/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
.
.
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base@21.0.3/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)

ssl configuration are well mounted in the docker container:

> docker exec -it da95f114b1f9 ls -al /etc/jikkou/secrets
total 20
-rw-r--r--    1 1000     1000          4892 Jun 19 15:55 kafka.producer.keystore.jks
-rw-r--r--    1 1000     1000          1318 Jun 19 15:56 kafka.producer.truststore.jks

What is weird is that when running a kafka cli commands no issue to connect to the cluster:

> kafka-configs.sh --bootstrap-server 0.0.0.0:39092 --command-config security/kafka/user-configs/client_config_ssl --describe --entity-type users
SCRAM credential configs for user-principal 'ksqldb' are SCRAM-SHA-256=iterations=4096

Here is the client_config_ssl file used with kafka cli :
```
security.protocol=SASL_SSL
ssl.truststore.location=./security/kafka/ssl/certifs/clients_certifs/kafka.producer.truststore.jks
ssl.truststore.password=confluent
ssl.keystore.location=./security/kafka/ssl/certifs/clients_certifs/kafka.producer.keystore.jks
ssl.keystore.password=confluent
ssl.key.password=confluent
ssl.endpoint.identification.algorithm=
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="admin" \
    password="admin-secret"; 
```

And here the Jikkou config file with the same parameters 

```
{
  "currentContext" : "confluent_docker_sandbox_ssl",
  "confluent_docker_sandbox_ssl" : {
    "configFile" : null,
    "configProps" : {
      "kafka.client.bootstrap.servers" : "0.0.0.0:39092",
      "kafka.client.security.protocol" : "SASL_SSL",
      "kafka.client.sasl.mechanism" : "SCRAM-SHA-256",
      "ssl.keystore.location" : "/etc/jikkou/secrets/kafka.producer.keystore.jks",
      "ssl.keystore.password" : "confluent",
      "ssl.key.password" : "confluent",
      "ssl.truststore.location" : "/etc/jikkou/secrets/kafka.producer.truststore.jks",
      "ssl.truststore.password" : "confluent",
      "ssl.endpoint.identification.algorithm" : "",
      "kafka.client.sasl.jaas.config" : "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"jikkou\" password=\"jikkou-secret\";"
    }
  }
}
```

**To Reproduce**
Have a kafka cluster running with SASL_SSL security protocol.
Run the below Jikkou command 
`docker run -it --net host --mount type=bind,source=./jikkou/jikkouconfig,target=/etc/jikkou/config --mount type=bind,source=./jikkou/kafka-topics.yaml,target=/etc/jikkou/kafka-topics --mount type=bind,source=./security/kafka/ssl/certifs/clients_certifs,target=/etc/jikkou/secrets streamthoughts/jikkou:0.34.0 create -f /etc/jikkou/kafka-topics/ --dry-run --logger-level=TRACE`

**Expected behavior**
An output of dry-run command without SSL error

**Runtime environment**
 - OS: Ubuntu 20.04.6
 - Jikkou: 0.34.0
 - Docker version: 26.1.4
 - Kafka Cluster Version: confluentinc/cp-kafka:7.6.1

**Additional context**
Found this issue here https://github.com/streamthoughts/jikkou/issues/425 where it was mentionned that SSL work without more information cause subject was more related to SR
Not sure if I missed a parameter required by Jikkou of if there is a bug here ?

**Comment by fhussonnois** [comment]
Hi @Antoine7773, I think you need to prefix all your ssl properties with `kafka.client.`

**Comment by Antoine7773** [comment]
Hello @fhussonnois  
Indeed it works well with the prefix "kafka.client". Thanks a lot !
