### ISSUE TITLE
Provide a list resource for SchemaRegistrySubject similar to KafkaTopicList

### ISSUE THREAD

**Issue by harshvardhan-j** [streamthoughts/jikkou#478]
**Is your feature request related to a problem? Please describe.**

We want to use the templating features provided by Jikkou to provide a simpler interface for our developers to check in their schemas and deploy them using Jikkou.

While we can currently leverage the templating capabilities for single schemas, we cannot do so for multiple schemas. With the help of this feature we can enforce global checks and compatibility rules also for our schemas.

**Describe the solution you'd like**

Provide a SchemaRegistrySubjectList resource that can be used with template files.

**Describe alternatives you've considered**
Running the template file on each schema input using xargs or some such capability to develop the resource files.

**Additional context**

**Comment by fhussonnois** [comment]
Hi @harshvardhan-j. The issue is fixed in the new bugfix release: https://github.com/streamthoughts/jikkou/releases/tag/v0.35.2 :)

**Comment by harshvardhan-j** [comment]
Thank you very much @fhussonnois. 🙏
