### ISSUE TITLE
Migrate integration tests to the new official docker image for Apache Kafka 

### ISSUE THREAD

**Issue by fhussonnois** [streamthoughts/jikkou#490]
**Is your feature request related to a problem? Please describe.**
The project uses [TestContainers ](https://testcontainers.com/) for integration tests.

Currently, all integration tests that require an apache kafka cluster are based on the `confluentinc/cp-kafka` docker image which can take some time to be downloaded and setup.

Here is the Java base class for kafka tests: https://github.com/streamthoughts/jikkou/blob/main/providers/jikkou-provider-kafka/src/integration-test/java/io/streamthoughts/jikkou/kafka/AbstractKafkaIntegrationTest.java

**Describe the solution you'd like**
Since release 3.8, an official docker image is available for Apache Kafka: https://hub.docker.com/r/apache/kafka-native

The Jikkou project could benefits from that new docker image if the `AbstractKafkaIntegrationTest` is changed to use that new docker image (see doc: https://testcontainers.com/modules/kafka/).

**Comment by selamanse** [comment]
@fhussonnois I'd like to try this. can you assign me plz ?

**Comment by fhussonnois** [comment]
closed by: https://github.com/streamthoughts/jikkou/pull/494
