### ISSUE TITLE
regarding 0.36 snapshot container

### ISSUE THREAD

**Issue by arnoldyahad** [streamthoughts/jikkou#495]
**Describe the bug**
Hey Jikkou team,
We wanted to upgrade to the unreleased 0.36 due to the change to how the results are printed (json as a one liner for us is very important for log parsing).
When testing 0.36 locally - it worked perfectly

but when trying to run the docker container - we can't run the jikkou command

**To Reproduce**
docker pull the jikkou container: https://hub.docker.com/layers/streamthoughts/jikkou/0.36.0-SNAPSHOT-java/images/sha256-94953a817dd702b7c96bdd611d51e6127a165ed0b5cbeb736656384782336734?context=explore
```
docker pull streamthoughts/jikkou:0.36.0-SNAPSHOT-java
```
(also `docker pull streamthoughts/jikkou:latest-java` as its the same)

try to run jikkou:
```
bash-5.1$ /app/bin/jikkou


```
and its stuck

**Expected behavior**
jikkou to run 

**Screenshots/Configs**

![image](https://github.com/user-attachments/assets/dac3f84d-55ec-437f-a86e-bba4c4dc5ea6)

**Runtime environment**
 - EKS 1.25 (amazon linux 2023)
 - Jikkou: 0.36.0

**Comment by arnoldyahad** [comment]
leaving the terminal open and trying again with `time` command i see it worked but it took around 40s:
```
bash-5.1$ time ./jikkou --help
Usage:
jikkou [-hV] [--logger-level=<level>] [COMMAND]


Jikkou CLI:: A command-line client designed to provide an efficient and easy way to manage, automate, and provision resources.

Find more information at: https://www.jikkou.io/.

OPTIONS:

  -h, --help      Show this help message and exit.
      --logger-level=<level>
                  Specify the log level verbosity to be used while running a command.
                  Valid level values are: TRACE, DEBUG, INFO, WARN, ERROR.
                  For example, `--logger-level=INFO`
  -V, --version   Print version information and exit.

CORE COMMANDS:
  apply                     Update the resources as described by the resource definition files.
  create                    Create resources from the resource definition files (only non-existing resources will be created).
  delete                    Delete resources that are no longer described by the resource definition files.
  diff                      Show resource changes required by the current resource definitions.
  get                       Display one or many specific resources.
  patch                     Execute all changes for the specified reconciliation mode.
  prepare                   Prepare the resource definition files for validation.
  update                    Create or update resources from the resource definition files
  validate                  Check whether the resources definitions meet all validation requirements.

SYSTEM MANAGEMENT COMMANDS:
  action                    List/execute actions.
  health                    Print or describe health indicators.

ADDITIONAL COMMANDS:
  api-extensions            Print the supported API extensions
  api-resources             Print the supported API resources
  config                    Sets or retrieves the configuration of this client
  generate-completion       Generate bash/zsh completion script for jikkou.
  help                      Display help information about the specified command.

real	0m39.157s. <= 40s!
user	0m3.696s
sys	0m0.236s
```

maybe its related to the snapshot being the one built from java and not ubuntu?

**Comment by fhussonnois** [comment]
Hi @arnoldyahad, I don't know why there is some docker images tagged with `-SNAPSHOT` (maybe an issue with the CI which I need to check). For using the latest version built from the main branch you can use one of the following images:
* `docker pull streamthoughts/jikkou:main` : The native image
* `docker pull streamthoughts/jikkou:main-java`: The JVM based-image.

I'm not sure to understand why you need to use a snapshot version. Is the latest stable release missing something for you? :  https://github.com/streamthoughts/jikkou/releases/tag/v0.35.4

**Comment by arnoldyahad** [comment]
hey @fhussonnois thanks a lot for the comment,
I was working on it before 0.35.4 was out and `main` was something that we didnt want to put in production in case it changes and breaks.

using 0.35.4 solves our issues so ill close this issue, thanks!
