### ISSUE TITLE
Jikkou artifact not available anymore in the maven repository since 0.33.3

### ISSUE THREAD

**Issue by bertrandcedric** [streamthoughts/jikkou#501]
**Describe the bug**
In the maven repository https://search.maven.org/search?q=jikkou, the jikkou artifact are not available anymore.
The last version available is the 0.33.3.

**Comment by fhussonnois** [comment]
Hi Cédric, I'm really sorry for that - it's seems I had an issue with the release process:

Jikkou v0.34.0 and v0.35.4 are available on Maven Central:
https://central.sonatype.com/artifact/io.streamthoughts/jikkou-core
