### ISSUE TITLE
Docker image tagged as "latest" is not the latest

### ISSUE THREAD

**Issue by gschmutz** [streamthoughts/jikkou#67]
Hi

Just started using Jikkou and realized that the image tagged as latest is not the 0.8.0 version (wanted to use the environment variable `JIKKOU_DEFAULT_KAFKA_BOOTSTRAP_SERVERS` :-).

Think it would be good to have latest on 0.8.0. 

Thanks for your work, I really just started using it but I think it is a really helpful tool!

**Comment by fhussonnois** [comment]
Hi @gschmutz, thanks for reporting this issue. The correct image has been pushed on Docker Hub.

```
$ docker run -it --rm streamthoughts/jikkou:latest --version
Unable to find image 'streamthoughts/jikkou:latest' locally
latest: Pulling from streamthoughts/jikkou
Digest: sha256:5cc11615fd5cf6150542cdceaacbaa8addfa4cfd6cadc83ca62820825265ff50
Status: Downloaded newer image for streamthoughts/jikkou:latest
Jikkou version v0.8.0
```
