### ISSUE TITLE
Option accepting multiple topic spec yaml files in one run

### ISSUE THREAD

**Issue by gschmutz** [streamthoughts/jikkou#69]
**Is your feature request related to a problem? Please describe.**

I'm in the process of including jikkou in a docker-compse.yml environment (generated using Platys) in a way that it just runs once at the beginning when the stack is started and whenever a `docker-compose up -d` is done. For that it would be nice if muliple topic-specs.yml file could be used in one run of jikkou. 

**Describe the solution you'd like** 
It would be nice if we could pass a pattern instead of a hard-coded file path. So all files matching the file pattern would be read and used for the run. 

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by fhussonnois** [comment]
Hi @gschmutz, thank you for this improvement proposal. Currently, we are facing the same need on my actual project.

For example, we could add new CLI args:
* `file-name`: a glob pattern to specifiy filenames (i.e., the base file name with the leading directories removed).
* `file-dir`:  the base directory used for searching files that match the given pattern (By default, if no root directory is specified, `.` is used)

Note that all files will be processed sequentially, which means that the actual state of the cluster will be retrieved for each file. But, we could also imagine to merge, for example, all the topics of all the files to apply the changes at once.

**Comment by fhussonnois** [comment]
Hi @gschmutz, Jikkou 0.9.0 is available. This new release adds support for multiple YAML files as described in my previous comment.

**Comment by gschmutz** [comment]
@fhussonnois  thanks a lot, will try it in the comming days! Very nice!
